
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder:
  purge_keep_days: 3              # keep 3 days of data
  auto_purge: true                # let HA purge automatically
  purge_interval: 1               # purge once per day
  commit_interval: 3600           # flush data to disk once per hour
  include:
    entity_globs:
      - sensor.inverter_*
